services:
    backend:
        build:
            context: flask
            target: builder
        depends_on:
            - mongo
        environment:
            - FLASK_SERVER_PORT=9091
        stop_signal: SIGINT
        volumes:
            - ./flask:/src
    haproxy:
        command: sh -c 'haproxy -f /usr/local/etc/haproxy/haproxy.cfg -d -q -S /dev/stdout 2>&1 | tee -a /var/log/haproxy/haproxy.log'
        image: haproxy
        ports:
            - 64641:64641
            - 59292:59292
        volumes:
            - ./logs:/var/log/haproxy
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    mongo:
        image: mongo
    web:
        command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - backend
        environment:
            - FLASK_SERVER_ADDR=haproxy:59292
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/tmp/nginx.conf
